# Generated by Django 3.0.4 on 2021-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='eng_content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='eng_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.IntegerField(choices=[(2, 'English'), (1, 'Malayalam')], default=1),
        ),
    ]
