# Generated by Django 3.0.4 on 2021-08-18 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210818_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='blog',
            name='preparation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
