# Generated by Django 3.0.4 on 2021-08-31 04:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210818_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preparation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=2000, null=True), blank=True, null=True, size=None),
        ),
    ]
