# Generated by Django 3.0.4 on 2021-09-12 15:18

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210912_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preparation',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
