# Generated by Django 3.0.4 on 2021-09-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210930_1453'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
