# Generated by Django 3.0.4 on 2021-09-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210930_1509'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='CATEGORY',
        ),
        migrations.AlterModelTable(
            name='cuisine',
            table='CUISINE',
        ),
        migrations.AlterModelTable(
            name='post',
            table='POST',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='TAG',
        ),
    ]
