# Generated by Django 3.2 on 2022-02-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20220122_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preparation',
        ),
    ]
