# Generated by Django 3.0.4 on 2022-01-21 19:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20220122_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
