# Generated by Django 3.0.4 on 2022-01-21 19:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post12',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
