# Generated by Django 3.0.4 on 2022-01-22 10:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_remove_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post12',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
